apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: node-fp-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: olegbon/node-fp-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: config-project
