apiVersion: v1
kind: ConfigMap
metadata:
  name: config-project
  namespace: node-fp-kubernetes
data:
  REACT_APP_API_URL: "http://backend.node-fp-kubernetes.svc.cluster.local:5000"
  APP_PORT: "5000"
  DATABASE_HOST: "database"
  DATABASE_USER: "root"
  DATABASE_PASSWORD: "rootpassword"
  DATABASE_NAME: "myapp"
  JWT_SECRET: "my_secret_key"
